### PR TITLE
Fix `as` losing the current query chain scope

### LINKED ISSUE #1278: Aliasing QueryProxy without losing scope
I have the following ActiveNode class
````
[1] pry(main)> DD::Error.count
 CYPHER 17ms MATCH (n:`DD::Error`) RETURN count(n) AS count 
=> 30990
`````
a scope defined in order to filter the class:
````
  scope :active, -> { where(status: 'active') }
````
so that:
````
[4] pry(main)> DD::Error.active.count
 CYPHER 34ms MATCH (result_dderror:`DD::Error`) WHERE (result_dderror.status = {result_dderror_status}) RETURN count(result_dderror) AS result_dderror | {:result_dderror_status=>"active"}
=> 2646
[5] pry(main)> my_qp = DD::Error.active
=> #<QueryProxy  CYPHER: "MATCH (result_dderror:`DD::Error`) WHERE (result_dderror.status = {result_dderror_status})">
[6] pry(main)> my_qp.count
 CYPHER 33ms MATCH (result_dderror:`DD::Error`) WHERE (result_dderror.status = {result_dderror_status}) RETURN count(result_dderror) AS result_dderror | {:result_dderror_status=>"active"}
=> 2646
````
I need to alias the QueryProxy in order to do some dynamic filtering later on. However it doesn't seem to work.
````
[9] pry(main)> my_qp.as(:a).count
 DD::Error 13ms MATCH (a:`DD::Error`) RETURN count(a) AS a 
=> 30990
````
However using the following combination works properly:
````
[11] pry(main)> my_qp.query_as(:a).proxy_as(DD::Error, :a).count
 CYPHER 41ms MATCH (a:`DD::Error`) WHERE (a.status = {a_status}) RETURN count(a) AS a | {:a_status=>"active"}
=> 2646
````

Is this expected behaviour?
### Runtime information:

Neo4j database version:
`neo4j` gem version: 7.2.0
`neo4j-core` gem version: 6.1.4

### PR DESCRIPTION
**Pull request by ProGM**
Fixes #1278 

This pull introduces/changes:
 * `.as` doesn't break query chain anymore

Pings:
@cheerfulstoic
@subvertallchris

### CODE REVIEW

File: lib/neo4j/active_node/query/query_proxy.rb [hunk 1]
```diff
@@ -186,11 +186,8 @@ def <<(other_node)
         #
         # @return [QueryProxy] A new QueryProxy
         def branch(&block)
-          if block
-            instance_eval(&block).query.proxy_as(self.model, identity)
-          else
-            fail LocalJumpError, 'no block given'
-          end
+          fail LocalJumpError, 'no block given' unless block
```
Comment (cheerfulstoic) [inline lib/neo4j/active_node/query/query_proxy.rb]: This is a pet peeve of mine, so be warned ;)

From a standpoint of language, saying "fail unless X" is weird because most of the time you won't be failing.  It feels somewhat better to say "fail if not X" because it's supposed to be a rare case

File: spec/e2e/query_proxy_methods_spec.rb [hunk 2]
```diff
@@ -511,6 +511,26 @@ def destroy_called
...
+
+      it 'keeps the current context' do
+        query = Student.where(name: 'John').as(:stud)
+        expect(query.to_cypher).to include('(stud:`Student`)', ' WHERE ')
+        query.to_a
+      end
+
+      it 'keeps the current context with associations' do
+        query = Student.all.lessons.as(:less)
+        expect(query.to_cypher).to include('`Student`)', '(less:`Lesson`)')
```
Comment (cheerfulstoic) [inline spec/e2e/query_proxy_methods_spec.rb]: Is passing multiple arguments to `include` an RSpec thing?  Does it mean that we expect both of those strings to be included (like an `and`)?

File: lib/neo4j/active_node/query/query_proxy.rb (hunk 1 above)
Comment (ProGM) [inline lib/neo4j/active_node/query/query_proxy.rb]: @cheerfulstoic 
Rubocop 0.4 doesn't agree with you 
Just joking, I understand what you're saying 😜
I changed that thing because of a suggestion of it from my Editor, but no problem about restoring it ;)

File: spec/e2e/query_proxy_methods_spec.rb (hunk 2 above)
Comment (ProGM) [inline spec/e2e/query_proxy_methods_spec.rb]: Yup! It works like that

File: lib/neo4j/active_node/query/query_proxy.rb (hunk 1 above)
Comment (cheerfulstoic) [inline lib/neo4j/active_node/query/query_proxy.rb]: I've ignored that rubocop rule in a number of projects, but I couldn't remember if I had done that here.  I like your `if block.nil?` suggestion from Gitter

I'm not a fanatic, exactly, but I have participated in conversations like this one: https://github.com/bbatsov/ruby-style-guide/issues/329

**Comment by ProGM** [comment]
Changed to `if branch.nil?`. Waiting for CI, then merging! ;)
