### PR TITLE
Fix validations with unpersisted nodes and various bugs with associations

### LINKED ISSUE #1292: Associations change in `update` is not rollbacked when validations fail
```ruby
p = Post.find(some_id)
p.update(comments: [])
# => false
# The relations are saved even if update fails!!!
p.comments # => []
```

### PR DESCRIPTION
**Pull request by ProGM**
Fixes #1292 , #1273 and is a replacement for both #1288 and #1279

This pull introduces/changes:
 * Does not fire database when accessing to unpersisted associations
 * Fixes `.count` method on associations, that should ALWAYS fire the database, also if the cache is available (like active record does)
* Fixed `size` and `length` on associations, that should take account of @deferred_objects
* Added (and passed) all AR specs about relationships: https://github.com/neo4jrb/neo4j/blob/16143eec2a0c1cae8434282f0d7bf8456c49497d/spec/e2e/validation_association_spec.rb Thanks @klobuczek 

Pings:
@cheerfulstoic
@subvertallchris
@klobuczek

### CODE REVIEW

File: lib/neo4j/active_node/has_n.rb [hunk 1]
```diff
@@ -101,9 +114,12 @@ def cached?
       end
 
       def replace_with(*args)
-        @cached_result = nil
-
-        @query_proxy.public_send(:replace_with, *args)
+        nodes = @query_proxy.public_send(:replace_with, *args).to_a
```
Comment (cheerfulstoic) [inline lib/neo4j/active_node/has_n.rb]: Why not `@query_proxy.replace_with(*args).to_a`?

File: lib/neo4j/active_node/query/query_proxy_methods.rb [hunk 2]
```diff
@@ -39,6 +39,7 @@ def order_property
 
         # @return [Integer] number of nodes of this class
         def count(distinct = nil, target = nil)
+          return 0 if unpersisted_start_object?
```
Comment (cheerfulstoic) [inline lib/neo4j/active_node/query/query_proxy_methods.rb]: Returning `0` feels like we've made a query and gotten an answer.  Maybe this should be `nil`?

File: lib/neo4j/active_node/query/query_proxy.rb [hunk 3]
```diff
@@ -1,7 +1,9 @@
 module Neo4j
   module ActiveNode
     module Query
+      # rubocop:disable Metrics/ClassLength
```
Comment (cheerfulstoic) [inline lib/neo4j/active_node/query/query_proxy.rb]: `rubocop:disable` makes @cheerfulstoic :sadpanda:

Not saying this can't be fixed later ;p

File: lib/neo4j/active_node/has_n.rb (hunk 1 above)
Comment (ProGM) [inline lib/neo4j/active_node/has_n.rb]: @cheerfulstoic  Really don't know. I left as it was 😆 We can change it, I think ;)

File: lib/neo4j/active_node/query/query_proxy_methods.rb (hunk 2 above)
Comment (ProGM) [inline lib/neo4j/active_node/query/query_proxy_methods.rb]: @cheerfulstoic  This is how AR works... so, I wouldn't change that

File: lib/neo4j/active_node/query/query_proxy.rb (hunk 3 above)
Comment (ProGM) [inline lib/neo4j/active_node/query/query_proxy.rb]: You're right. Probably we should split the `QueryProxy` module a bit later ;P

File: lib/neo4j/active_node/query/query_proxy_methods.rb (hunk 2 above)
Comment (cheerfulstoic) [inline lib/neo4j/active_node/query/query_proxy_methods.rb]: I thought it might be, thanks ;p

**Comment by cheerfulstoic** [comment]
:+1:

**Comment by ProGM** [comment]
Merged, thank you for your suggestions @klobuczek !
